# Generated by Django 3.1.6 on 2021-02-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Name',
        ),
        migrations.AddField(
            model_name='booking',
            name='First_Name',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='booking',
            name='HeadCount',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='Last_Name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
